language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: WhujKKU0JLbGBAuRhKxD0SECG2iztERtA7s/9/NSSAKMg/M2xDrO8Lq4M+R8PnJ8m1FHxXRFdJsQW21kahG/KEeZw7Wt95gbLOWHkj9xxgfLn0gXkkyP/kvbi6Fi8IfSSHBk7Cm8xPbn5F5/58kkbSGmPr4vHtzi6PAkNUg6nerqiKTUHqZ19NhMdCZg22b5XEYvsvMaSA8EybT0HahLIkjYJx3LJ4XKWjDW0/n0yUZHWf2yUYkf4MCvxvHXAnnLhUBv3PbsQcFgFQpIIFESL6SRzjiF/Ip4hApDCVJkcq58p8UyxdvIDBsqni8JtLKbBhgfQUWrbMQMen0nDrrbnRdd/1RW3tUwBZCC1koVnwW2cL9e8LrMz2CIOqGoY46AyHejWiemkLlpamnVdAgWPi9opkVg8mingpi2WVvJ03qzY25X5whsukfqB03J5ffu7nNmUaYn4n5EzsfUvBe7zcKNDFA21IvsURaZ8mbRmtbEZjbJYEP1DK+GCKxfk9r3kv+XuJi8KYPSQgsPJ1Rz9yk3Y/no/07UJJZ34lqFe4GIWnKeYZImZE5dHwIXqYMaB03yLyzhLYPRJQaShK3UELc4VZWIL2yVULmTbZrgwQkl45GNz01Ic4fnVJpttJLMta6gSjXEdpCsUMruxfb5vKl0fdhCpIu9SmAsVsgZLwY=
  app: tailored-knits-react
  on:
    repo: GilliganL/tailored-knits-react
