language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: bPj0Us47aTc/nTtH8iVFDQQG8fkLwEdvyZlzKNzqvzZ0rk7nztiXXsNzyn9jbHCJ2wREJthRbROw1ou6wzyCowuE/c1B09Ok474W6EPhXjwp591wyi/BfHbCFfjrU6OtKFpUOyb2T46x4ZqmvxtJkLKYym0n6fqZib5F5gcabttiGIAf1L0Qk1/8lUbXYeZpW5JiXstsyk53ewGwWuH/P3fjdGB4OSZebstNYLd0C6FO59TILUqz52b9WvaQHJ7mXGntzLLDoIN9FaZP3QmmXmWVS2wrTpAPUF9iyjF9g0hvdftObW649Y7JynU/IkljlRm9xhJkSIYb6/SpbpSvWAWkpErdUif9zHiw5vQxyu9JxJFbFIxWGnyyi8v5zqJL+1grVHTYzpdaeX+muc9pYrx2xzWEsNEycytDjRu6j8Cv57qifLptXSt4TXQb3F+ttQlMtTl8oEup8S2I/5bZLKM5pzEVkH/a0jDQNl87mM1tVgtX03HENecsaJPs2yx/qo01gpSzToIAJHta8Ug9cYnByM+f5/8lPukTd/EGfmOJ/JR4pQLVOgV+nmYrFsfffqkH5bBW0eQdWj+0id3ln2vZJhTK7SotewSfcarFyUO7wNreBZWFRKAuh7+GGhLeStlfnJFp55PMa4AjwEFc8PmTmlRqKMNBEaDMyQpFNOA=
  app: tailored-knits
  on:
    repo: GilliganL/tailored-knits-react
